import './AboutPage.css'
import { useNavigate } from 'react-router-dom'

function AboutPage() {
  const navigate = useNavigate()

  return (
    <div className="about-page">
      <header className="about-header">
        <div className="about-title">About</div>
        <div className="about-subtitle">Understanding Media Bias</div>
      </header>

      <div className="about-content">
        <section className="about-mission">
          <div className="mission-title">Our Mission</div>
          <div className="mission-text">
            We help readers identify how wording, framing, and tone can shape
            political perception. Our goal is to make bias analysis readable,
            transparent, and useful in day-to-day news consumption.
          </div>
        </section>

        <section className="about-methodology">
          <div className="methodology-title">Methodology</div>
          <div className="methodology-text">
            <p>
              Each submitted article is analyzed for sentiment, loaded language,
              and framing patterns that often correlate with political slant.
              Results are surfaced as interpretable scores so users can compare
              articles and understand why they were classified a certain way.
            </p>

            <p>
              The sentiment score is on a scale of -1 to 1, where -1 indicates negative sentiment and 1 indicates positive sentiment.
            </p>

            <p>
              The bias score is on a scale of -1 to 1, where -1 indicates left-leaning bias and 1 indicates right-leaning bias.
            </p>
          </div>
        </section>

        <section className="about-disclaimers">
          <div className="disclaimers-title">Disclaimers</div>
          <div className="disclaimers-text">
           <p>
              The bias and sentiment scores generated by this application are based on
              automated analysis and may not capture the full context of an article.
            </p>

            <p>
              Some new sources may be blocked due to paywall or web-scraping blockers.
            </p>

            <p>
              Users are encouraged to read articles in full and consider multiple
              sources when forming opinions.
            </p>
          </div>
        </section>
      </div>

      <div className="about-footer">
        <button
          className="about-button about-button-secondary"
          onClick={() => {
            navigate('/dashboard')
          }}
        >
          Back To Dashboard
        </button>

        <button
          className="about-button about-button-primary"
          onClick={() => {
            localStorage.removeItem('token')
            navigate('/')
          }}
        >
          Log Out
        </button>
      </div>
    </div>
  )
}

export default AboutPage